language: java

branches:
  only:
    - master
    - develop

jdk:
  - openjdk10
  - openjdk11
  - oraclejdk9
  - oraclejdk11

before_install:
  - echo "JDK is $TRAVIS_JDK_VERSION"
  - if [ $TRAVIS_JDK_VERSION = "oraclejdk11" ]; then echo "JDK match"; fi
  - if [ $TRAVIS_JDK_VERSION = "oraclejdk11" ]; then sudo apt-get install jq; fi
  - if [ $TRAVIS_JDK_VERSION = "oraclejdk11" ]; then wget -O ~/codacy-coverage-reporter-assembly-latest.jar https://github.com/codacy/codacy-coverage-reporter/releases/download/6.0.0/codacy-coverage-reporter-6.0.0-assembly.jar; fi

after_success:
  - if [ $TRAVIS_JDK_VERSION = "oraclejdk11" ]; then java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r build/reports/jacoco/test/jacocoTestReport.xml; fi
